/// Flutter icons TangaCustomIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  TangaCustomIcons
///      fonts:
///       - asset: fonts/TangaCustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class TangaCustomIcons {
  TangaCustomIcons._();

  static const _kFontFam = 'TangaCustomIcons';
  static const _kFontPkg = null;

  static const IconData user_1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData photo_camera = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData log_out = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_arrow_2 = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_1 = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
